# Generated by Django 5.0.2 on 2024-02-26 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='approved_limit',
        ),
    ]
