# Generated by Django 5.0.2 on 2024-02-27 08:00

import customer.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_approved_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=customer.models.CustomAutoField(primary_key=True, serialize=False),
        ),
    ]
